development:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
 # :user_name: inseremail
 # :password: insertpassword
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
 # :user_name: inseremail
 # :password: insertpassword
  :enable_starttls_auto: true