development:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :user_name: ixglobalservice@gmail.com
  :password: 710cb6fa3b37f629afe29b4ba57f7c27
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :user_name: ixglobalservice@gmail.com
  :password: 710cb6fa3b37f629afe29b4ba57f7c27
  :enable_starttls_auto: true