#development:
 # :address: smtp.gmail.com
 # :port: 587
  #:domain: gmail.com
 # :authentication: plain
# # #:password: pwd
 # :enable_starttls_auto: true
#production:
 # :address: smtp.gmail.com
 # :port: 587
 # :domain: gmail.com
 # :authentication: plain
 # :user_name: ex@example.com
#  :password: pwd
 # :enable_starttls_auto: true